modLoader="javafml"
loaderVersion="${forgeVersionRange}"
license="MIT"
issueTrackerURL="https://github.com/MCXTeam/UnicoreConnect/issues"

[[mods]]
modId="unicoreconnect"
version="${modVersion}"
displayName="UnicoreConnect"
authors="UnicoreProject"
description='''
Интеграция сервера с UnicoreCMS: экономика, время в игре, склад покупок, донат-группы и баны.
'''

[[dependencies.unicoreconnect]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="SERVER"

[[dependencies.unicoreconnect]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftVersion}]"
    ordering="NONE"
    side="SERVER"
