import org.apache.tools.ant.filters.ReplaceTokens

defaultTasks 'build'

allprojects {
    group 'uno.unicore'
    version '1.1.0'
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(8)
        }
    }

    repositories {
        mavenCentral()
        maven {
            url "https://hub.spigotmc.org/nexus/content/repositories/snapshots"
        }
        maven {
            url "https://repo.spongepowered.org/maven"
        }
        maven {
            url "https://repo.codemc.io/repository/maven-public/"
        }
        maven {
            url "https://ci.frostcast.net/plugin/repository/everything"
        }
        maven {
            url 'https://jitpack.io'
        }
        maven {
            url "https://repo.essentialsx.net/releases/"
        }
        maven {
            url "https://repo.papermc.io/repository/maven-public/"
        }
        maven {
            url = "https://repo.aikar.co/content/groups/aikar/"
        }
        maven {
            url = "https://repo.extendedclip.com/content/repositories/placeholderapi/"
        }
    }

    processResources {
        filter(ReplaceTokens, tokens: ["app.version": this.project.version])
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}

configure([
    project(':UnicoreConnect-common'),
    project(':adapters:permissions:UnicoreConnect-permissions-luckperms'),
    project(':adapters:permissions:UnicoreConnect-permissions-forgeessentials'),
]) {
    apply plugin: 'maven-publish'

    publishing {
        publications {
            core(MavenPublication) {
                from components.java
            }
        }
    }
}
